version: "3.4"

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "80:3000"
    env_file:
      - ./.env
    stdin_open: true

  backend:
    build: ./backend
    volumes:
      - ./backend/src:/app/src
      - ./geoip-data:/geoip-data
    ports:
      - "3000:3000"
    env_file:
      - ./.env

  geoip:
    image: maxmindinc/geoipupdate
    volumes:
      - ./geoip-data:/usr/share/GeoIP
    env_file:
      - ./.env
